### ISSUE TITLE
[Tarea 1 P2] Toma de Cursos Aprovados

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#10]
Hola, estoy confundido con la toma de cursos ya aprobados. El enunciado y las preguntas me hacen entender que se esta haciendo un programa que planifica las clases que puede tomar. Sin embargo, la descripción y el segundo argumento de ```approved_at``` me hace pensar que el programa es más parecido a un historial de un estudiante. ¿Cual es la interpretación correcta? ¿Hay que hacer un ```course_on``` a las clases aprobadas o se ignoran?

**Comment by vicentevegaulloa** [comment]
Hola @Jpuc1143 !

Las clases aprobadas deben ignorarse cuando se trata del predicado `course_on`. La forma en la que tienes que verlo es que te pasamos una cantidad de ramos en la malla del alumno y tu meta es planificar el resto de su carrera. En esta malla van a haber ramos aprobados y otros que deben ser asignados a algún punto futuro de su carrera. En el enunciado, en la imagen del visualizador, intentamos mostrar que los ramos aprobados aparecen más opacos que los que se asignan.

Espero haberte ayudado. Si te quedan dudas pregunta nomás y yo feliz de ayudarte :)
