### ISSUE TITLE
[Tarea 1 - Pregunta 2]  Cursos aprobados con cursos asignados

### ISSUE THREAD

**Issue by ferperezh** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#12]
Los semestres que tengan cursos aprobados pueden tener semestres cursando, es decir, Course_on. Si es así se considera los cursos aprobados como entre los asignados para cada semestre, es decir, si hay un semestre con semestre asignados y no asignados la suma puede ser mayor a 5 ?

**Comment by ferperezh** [comment]
Con eso mente ramos que sean prerequisitos y correquisitos de ramos aprobados se debe cumplir la norma ?

**Comment by vicentevegaulloa** [comment]
Lo lógico es que los semestres con cursos aprobados no tengan semestres asignados (course_on) ya que esto significaría que se está asignando un ramo en un semestre que ya pasó. Esto no tiene mucho sentido pero no pusimos la restricción en el enunciado. Esto quiere decir que pueden dejar pasar esta restricción y no se les quitará puntos. 

Por otro lado, la restricción de máximo 5 cursos en un semestre sólo aplica a los cursos asignados (course_on).

**Comment by morbeta1234** [comment]
@vicentevegaulloa En relación a lo que comentas del máximo 5 cursos asignados, entonces se consideraría bueno un resultado como este? O hay que limitar a 5 ramos en total por semestre, sean tanto aprobados o no aprobados (por cursar)?
Gracias de antemano!

<img width="1375" alt="Screen Shot 2022-09-16 at 17 51 10" src="https://user-images.githubusercontent.com/76602431/190730558-2dc48997-55f0-4fee-9a55-addeb2ad1cc2.png">
