### ISSUE TITLE
[Tarea 1 - Pregunta 2] Error ejecutar tests

### ISSUE THREAD

**Issue by mhrobles** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#13]
Estoy intentando correr la línea de código expresada en el enunciado, pero me da un error, no se que es lo que podría estar pasando 
![image](https://user-images.githubusercontent.com/37165583/190280885-307c0b8f-a053-45c0-a022-f0723b8c650c.png)

**Comment by ignacio-quera** [comment]
Tengo la misma duda 🆙

**Comment by vicentevegaulloa** [comment]
Hola! 

La X es un valor referencial. Si te fijas, no existe un test X, la idea es que reemplaces por el número del test que quieres probar. Lo mismo pasa con el bound. El bound representa la cantidad de semestres donde quieres distribuir los ramos a cursar.
