### ISSUE TITLE
[Tarea 1 P2] Creación de los modelos e independencia de las actividades.

### ISSUE THREAD

**Issue by LaSamada** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#14]
Hola!, en la pregunta 2 se establece que nuestra función es la creación de las reglas, debemos crear las combinaciones de course_on(C, S) también?. Y además, se puede probar la funcionalidad de la actividad 1 de la P2 sin hacer la Act 2?.
Muchas gracias de antemano.

**Comment by LaSamada** [comment]
Aprovecho de sumar la pregunta si se pueden crear predicados que ayuden o faciliten el problema (como para contar algo en especifico) y si se puede en una línea solucionar 2 reglas.

**Comment by vicentevegaulloa** [comment]
Hola! 

Sí deben crear las combinaciones de course_on. Con respecto a tu segunda pregunta, sí se puede probar las restricciones de la P2.1 sin hacer la P2.2. Además, sí se pueden crear predicados que no estén en el enunciado para cumplir con el objetivo. Y si lo logras y lo dejas explicado, también puedes solucionar dos restricciones en una línea.
