### ISSUE TITLE
[Tarea 1 P2] Test 7

### ISSUE THREAD

**Issue by nkantorn** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#15]
Hola!!
Tengo una duda sobre el test 7. En este sale ```approved_at(optativo_5, 2).```  y ```approved_at(c2, 2).```, sin embargo más arriba se especifica ```dictates_on(optativo_5, 1).``` y ```dictates_on(c2, 1).```, lo que es contradictorio ya que el curso fue aprobado en un semestre par, pero se dicta en semestres impares. ¿ Podemos asumir que estos cursos se dictán igualmente en semestres pares? 
Muchas gracias!!

**Comment by NickCastillo** [comment]
Hola! Perdon, se nos debe haber escapado ese detalle. La respuesta es sí, pueden asumir que ambos se dictan en ambos semestres y editar el test de tal manera que no se contradigan. De igual manera pueden editar los tests de las formas que quieran para asegurarse que sus programas entreguen modelos correctos

**Comment by nkantorn** [comment]
Gracias!
