### ISSUE TITLE
P2 - T1 : significado de "bound"

### ISSUE THREAD

**Issue by totoiii** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#16]
Me confundi respecto a cuánto vale bound para cada uno de los test. 
Lo que entiendo es que por ejemplo para el test 1 el valor de bound es 1, pero entonces no habrán semestres para asignarle a los 10 ramos ya que con un semestre  y con la restriccion de 5 ramos maximo. Y si junto esto con que los semestres que no esten aprobados deben tener un unico semestre asignado, no habrá ningun modelo que cumpla con ambas restricciones.
Espero se entienda mi razonamiento, me gustaria saber qué es lo que estoy pensando mal

**Comment by NickCastillo** [comment]
La variable "bound" pueden usar libremente a medida que pruebas los distintos tests. Efectivamente si pruebas con bound=1 un test con mas de 5 ramos, tu programa debería decirte que el problema no es satisfacible lo que seria un razonamiento correcto.  Teniendo eso, luego puedes probar con bound > 1 y deberías estar recibiendo modelos correctos.
