### ISSUE TITLE
[Tarea 1] Formato de entrega PDFs

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#18]
Para entregar los PDFs asociados a las partes 2 y 3, ¿simplemente los añadimos a las carpetas DCCursos y DCCharcos respectivamente?

**Comment by vicentevegaulloa** [comment]
Hola!

Así es. Lo dejan en la carpeta de cada pregunta.
