### ISSUE TITLE
[Tarea 1] DCCharcos código base

### ISSUE THREAD

**Issue by tvonplessing** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#19]
Estuve probando mi código para el test 1 y 2 y funciona perfectamente, pero al incluir otro robot (test 3) deja de funcionar. Pensé que era un error del código que yo escribí, pero luego modifiqué el test case 3 eliminando los obstáculos, charcos y flotadores y utilice el código base que nos entregan y me arroja UNSATISFIABLE. ¿Será que el código base tiene algún error?

**Comment by Kevinnevik** [comment]
Tengo la misma duda, probe el caso base old.lp con el código que nos dieron y con un bound de 14 y me da insatisfacible.

**Comment by Jamesmoreno21** [comment]
Hola! 

El código base debería ser funcional para old.lp y si el problema está después de que hayan implementado su solución les recomiendo que revisen bien las reglas que han definido y el bound que le entregan al problema. 

De todas formas lo revisaré en detalle y les informaré acá cualquier situación durante el día

Saludos y ánimo con la tarea!

**Comment by Kevinnevik** [comment]
Hola, probando el código base y el test old.lp con un bound de 14 me sale que el problema es UNSATISFIABLE.

**Comment by Jamesmoreno21** [comment]
Hola @Kevinnevik! Podrías sacar un pantallazo de cómo estás corriendo el código en la terminal?
