### ISSUE TITLE
Problema instalación clingo en mac

### ISSUE THREAD

**Issue by matiasconcha11** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#2]
Hola! Estoy intentando instalar Clingo pero se me generan problemas al ejecutar 
`brew install clingo` . Adjunto imagen de lo que me arroja el terminal. 
<img width="556" alt="Captura de Pantalla 2022-08-16 a la(s) 17 20 14" src="https://user-images.githubusercontent.com/89225573/184987277-02138d19-bfc7-4f01-ab48-43b677c7a38b.png">

**Comment by BrunoFarfan** [comment]
Hola!
Por lo que veo te está dando un error de permiso.

Prueba correr el comando pero escribiendo `sudo` antes.
Si no funciona esto, puede deberse a que quizás tu usuario (del compu) no tiene los permisos requeridos.

**Comment by matiasconcha11** [comment]
Hola! Intente con sudo pero me dice que es muy peligroso y no deja hacerlo. Mi usuario es el único en el computador y tiene permisos para leer y escribir en esa carpeta por lo que no entiendo muy bien de donde nace el problema.

**Comment by NickCastillo** [comment]
Hola! Como una alternativa podrías probar instalando clingo con `port` (así lo instale yo por lo menos y toma un minuto)
- Instalación de MacPorts: https://www.macports.org/install.php
- Comando para instalar clingo (con comando `port`): https://ports.macports.org/port/clingo/

**Comment by matiasconcha11** [comment]
Muchas gracias! Finalmente pude descargarlo borrando las carpetas que me arrojaban error asi que todo bien ;)
