### ISSUE TITLE
[T2] DCCharcos: Decidir colocarse un flotador

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#20]
Hola! Una consulta para que un robot decida colocarse un flotador no hay una acción determinada para ello, me refiero a una como la hay para el caso de las cajas(liftbox), es válido para el desarrollo de esta parte crear una por nuestra cuenta aunque esto requeriría que modificará el código base, pregunto esto más que nada porque en el enunciado dice que es necesario modificar el código base para la parte 2(de los portales) pero no dice nada respecto a la primera o no es la idea que creemos nuevas acciones?

**Comment by Jamesmoreno21** [comment]
Hola @RonaldoSosa ! La idea de que no modificar el código base es que las reglas que ya existen no se modifiquen, si no que únicamente agregues líneas para la funcionalidad, por lo que si estimas crear una nueva acción puedes hacerlo.

Para la parte 2 sí  deberas modificar algunas líneas del código base.

Saludos!!
