### ISSUE TITLE
[Tarea1 P3] Decidir usar un portal

### ISSUE THREAD

**Issue by totoiii** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#21]
Hola!
Tengo una duda respecto al uso de portales, el enunciado no dice nada sobre si un robot puede decidir usar un portal si usarlo o no en el caso de que esté en la posicion de la entrada de este. ¿Debe ser obligación que el robot se teletransporte en el caso de que se encuentre en la posición de una entrada de un portal? o puede decidir no hacerlo y pasar por encima de este.

**Comment by Jamesmoreno21** [comment]
Hola @totoiii !! La idea de los portales es que si un robot entra en una casilla con un portal, obligatoriamente se debe teletransportar a la salida de este. 

Su desición es si entra a la casilla o si va a otra casilla.

Ánimo con la tarea!!
