### ISSUE TITLE
Preguntas P1 y P2

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#22]
Hola, me surgieron las siguientes dudas:
P1- En esta parte debo asumir que las personas están en un círculo, es decir la persona 5 está a la izquierda de la persona 1 o la persona 1 está a la derecha de la persona 5, o solamente están en línea recta y que la persona 1 con la 5 no están conectadas.
P2- Se puede asumir que si las personas aprobó mínimo un ramo en algún semestre, entonces no se debe  asignar ramos en ese semestre. Por ejemplo, si un alumno aprobó solo cálculo 1 en el semestre 1, entonces no puedo asignar otros cursos como álgebra lineal en el primer semestre.

**Comment by j4vito** [comment]
1) Están en fila, como en la foto del enunciado.

2) Sí es posible asignar otros ramos a un semestre con cursos aprobados, mientras se cumplan las reglas.

**Comment by Kevinnevik** [comment]
Okey, pero en el segundo punto la cantidad de ramos que se asignaron más los cursos aprobados en un semestre deben ser a lo más 5?
