### ISSUE TITLE
[P3 T1] Diferencia entre predicados.

### ISSUE THREAD

**Issue by LaSamada** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#24]
Hola!, en el enunciado se establece que existe robotLiftBox, pero en el código también existe un boxOnRobot, hay alguna diferencia entre ellas?
Gracias de antemano!.

**Comment by Jamesmoreno21** [comment]
Hola @LaSamada! Sí, hay una diferencia:
- robotLiftBox(R, B, T) indica que el robot R decide levantar la caja B en el tiempo T, es decir, que ya ejecutó la acción liftbox en T.
- boxOnRobot(B, R, T) señala que el robot R lleva una caja B en el tiempo T.

Una se aborda al momento en que levanta la caja y la otra a los estados de la caja sobre un robot.

Éxito con la tarea!
