### ISSUE TITLE
[T1-P2] Problema con tests

### ISSUE THREAD

**Issue by mhrobles** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#26]
Al momento de ejecutar el test 1 me aparece un error que no parece estar relacionado con el código que puse, no se como solucionarlo, necesito ayuda con esto :c 
![image](https://user-images.githubusercontent.com/37165583/191614694-744dfc79-a736-46c6-8dcd-a67d99c5ccd5.png)

**Comment by jo00** [comment]
hola pudiste resolverlo? a mi me tira "*** ERROR: (clingo): In context '<clingo>': multiple occurrences: 'models'"

**Comment by mhrobles** [comment]
no, pero mi error fue porque no me fijé que estaba ejecutando el cmd desde otra ruta jajaja
