### ISSUE TITLE
[Control 4] Duda pregunta de función Best-First-Search

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#29]
Hola, respecto al control 4 quedé con duda en la siguiente pregunta:
<img width="585" alt="Captura de Pantalla 2022-09-26 a la(s) 22 13 51" src="https://user-images.githubusercontent.com/62019329/192408707-48e1ba09-f9c9-462a-b1c3-9398818f2afe.png">
Mi pregunta es cual es la explicación de esto, ya que no entiendo como saber esto. Muchas gracias.

**Comment by tcouso** [comment]
Hola! 
Si te fijas bien, cuando d(s) retorna el número de acciones que se ejecutaron para producir s desde el estado inicial, lo que está pasando es que los estados donde d(s) sea más grande serán los que más recientemente hemos visitado, mientras que los estados donde d(s) sea más chico serán los que visitamos hace más tiempo. Si ordenamos Open de acuerdo a esa función, tendremos una estructura de tipo FIFO (los primeros que entran son los primeros que salen), de modo que Best-First Search se comportará como Búsqueda en Amplitud. La sección 3.3.2 de Russell y Norvig tiene más detalles de cómo cambia Best-First Search en base a cómo ordenes la cola Open.
Saludos!
