### ISSUE TITLE
Instalacion de clingo en mac

### ISSUE THREAD

**Issue by Benyo27** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#3]
Hola!

Para instalar segui la capsula de instalacion, corriendo el comando ```brew install clingo```, pero este instala la version 5.5.2 por defecto. No se si sera un problema.

Gracias:)

**Comment by vicentevegaulloa** [comment]
Hola! 

No se como lo podrías hacer para bajar de versión, pero estuve investigando y para los programas con los que van a trabajar, no deberían tener problemas si ocupan cualquiera de las dos versiones.
