### ISSUE TITLE
[T2 - P 1.5] Bidirectional Search

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#30]
En la Actividad 5 se pide describir Bidirectional Search. He encontrado páginas de internet que consideran Bidirectional Search como algoritmos genéricos que realizan las dos búsquedas _forward_ y _backward_ y otras que definen Bidirectional Search como el algoritmo que usa esta aproximación específicamente con BFS. ¿Por cuál de las dos definiciones se pregunta?
Gracias!

**Comment by Skablop** [comment]
Hola,

Como es una pregunta de investigación, no hay problema en que menciones que encontraste dos definiciones (recuerda referenciar tus fuentes).

Saludos.
