### ISSUE TITLE
[T2 - P1.1] Heurística Weighted A*

### ISSUE THREAD

**Issue by aplaza2** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#32]
Hola, en la pregunta 1.1 se dice que _Anytime_ recibe un estado inicial, un peso y un límite de expansiones, pero no dice que recibe una heurística (lo que sí hace A*). ¿Podemos hacer que se le tenga que agregar al llamar el algoritmo o hay que obtener la heurística de otra manera? 

Además, también está el asunto de cómo ejecutar el algoritmo. En las instrucciones solo se indica que hay que crear la clase, ¿pero se puede modificar run.py para programar la ejecución?

**Comment by sebaguerrap** [comment]
Hola @aplaza2 . Efectivamente, el algoritmo debe recibir una heurística como input.

Sobre cómo ejecutar el algoritmo, el enunciado dice que debes especificar tú como hacerlo en el pdf asociado a esta pregunta. Si quieres modificar ```run.py``` te recomiendo crear un nuevo archivo que sea copia de ```run.py``` y que esté diseñado para correr el nuevo algoritmo.
