### ISSUE TITLE
T.2 P1.1 limite de expansiones

### ISSUE THREAD

**Issue by brayan788** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#34]
Hola cuando se llega al limite de expansiones, debo preguntar un nuevo limite o el algoritmo debe resolver hasta llegar al objetivo??

**Comment by vicentevegaulloa** [comment]
Hola!

Cuando alcanzas el límite de expansiones el algoritmo se acaba. Eso quiere decir que el último yield que hubo corresponde a tu solución final.

**Comment by Mamunoz42** [comment]
Hola!

Pero aquí tengo una duda, se supone que el usuario podría decidir si revisar más o no, esto se debe hacer solicitando algún input o de que forma se pide hacerlo? Es que no me queda muy claro
