### ISSUE TITLE
T.2 P1.1

### ISSUE THREAD

**Issue by tvonplessing** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#37]
Hola! Al cambiar los keys de los nodos en open y luego utilzar reorder, no se actualizan los valores del open, habrá algo malo con la función?

**Comment by sebaguerrap** [comment]
Hola @tvonplessing . Efectivamente hay un error en el método ```reorder```. Pronto subiremos el archivo con la modificación al repositorio de la tarea. Te dejo de igual forma el método corregido:

```python
def reorder(self):
    for i in range(2, self.size+1):
        self.percolateup(i, self.array[i])
```
