### ISSUE TITLE
T2 Parte 2: Actividad 1

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#38]
Hola! En el PDF de la tarea dice que en el archivo status.py hay un atributo llamado "last move" pero revisando el archivo no hay ninguno con dicho nombre solo uno llamado "last_opponent", se refiere a ese atributo?. Adjunto una imagen del archivo status.py
![Captura de pantalla (99)](https://user-images.githubusercontent.com/62029138/195963136-bc6d3ec5-750b-429d-ac27-08c69afdddf5.png)

**Comment by Skablop** [comment]
Tienes razón,  se nos fue cambiar el nombre en el pdf 😓. Justamente como dices el atributo es last_opponent.

**Comment by RonaldoSosa** [comment]
Valee!!! Gracias
