### ISSUE TITLE
[T2 1.6] Comparacion Bidirectional Search con A*

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#39]
En el apartado b se pide comparar el algoritmo bidireccional entregado con la implementación de A*. ¿Hay que comparar el algoritmo _solver2_ directamente con A* o se refiere a la versión de _solver2_ incluyendo heurísticas que se debe explicar en (a)?
Muchas gracias!

**Comment by vicentevegaulloa** [comment]
Hola! 

Se debe comparar A* con el _solver2_ entregado. El _solver2_ con heurísticas no es necesario programarlo.
