### ISSUE TITLE
T2 pregunta 2.1

### ISSUE THREAD

**Issue by Fuentes149** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#41]
Hola tengo un problema corriendo el archivo main de la parte 2 de la tarea me aparece este error en la linea 91:
SyntaxError: Non-ASCII character '\xc3'

![Captura de Pantalla 2022-10-15 a la(s) 18 02 16](https://user-images.githubusercontent.com/89354729/196007458-c4d92334-4dd8-45cf-8d56-a6e622e53134.png)

**Comment by Skablop** [comment]
No estoy 100% seguro, pero creo que puede ser porque en la línea 91 está el caracter "ñ" en un comentario. Ahora, normalmente eso no debería ser problema porque Python 3 usa por default UTF-8 para el encoding.

Ve si te resulta alguna de las siguientes cosas para resolverlo:
* Verifica que tu versión de python sea 3.x y no 2.x
* Deja la primera línea de main.py con lo siguiente: ``# -*- coding: utf-8 -*-``
* Borra la ñ y los tildes de los comentarios si es que nada de lo anterior funciona.

Avisa si lo puedes resolver.
