### ISSUE TITLE
T2 pregunta 2.1

### ISSUE THREAD

**Issue by Fuentes149** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#42]
Hola tuve un problema corriendo el archivo main.py, al iniciar el archivo me deja jugar pero cuando hago el primer movimiento en el juego me aparece el siguiente error y el juego se cae:
![Captura de Pantalla 2022-10-16 a la(s) 10 09 01](https://user-images.githubusercontent.com/89354729/196037169-581a3644-62c7-4af2-a00f-7535ab7e63c1.png)

**Comment by Skablop** [comment]
Hola,

He tratado pero no he podido replicar el error. Si no lo usas, te recomiendo que instales un entorno virtual con miniconda 

https://docs.conda.io/en/latest/miniconda.html

Los pasos serían :

* Instalar Miniconda y correr la consola de miniconda si estás en Windows (en linux basta reiniciar la consola).
* Crear un entorno virtual con el comando ``conda create --name tarea2 python=3.9``
* Activar el entorno virtual con ``conda activate tarea2``
* Instalar pygame en el entorno con pip

Y correr main.py desde el entorno.

Te recomiendo esto ya que así podemos aislar el error a un entorno común y ver si se mantiene.

Saludos.
