### ISSUE TITLE
[T2]Código base DCCanicas

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#43]
Hola 🖖🏽

Hoy mientras hacia mi tarea comencé a inspeccionar un poco el código base que se nos entrego y detecté al parecer un error (no estoy seguro, por eso escribo la issue). En el archivo `minmax.py`cuando se crea la variable `maximizing_player`, en esta es almacena un bool, sin embargo, la función `get_score`asume que se recibe un **int** que podría ser 0 o 1. Es ante esto que me surge la duda de si está bien el código.

<img width="807" alt="Captura de Pantalla 2022-10-16 a la(s) 17 38 19" src="https://user-images.githubusercontent.com/62019329/196057419-ba0e3e01-f9b3-49e5-bd09-8b55a9eb3b1c.png">

<img width="777" alt="Captura de Pantalla 2022-10-16 a la(s) 17 38 29" src="https://user-images.githubusercontent.com/62019329/196057450-8d456fea-d9f1-4ba7-9d41-45100f253dd4.png">

<img width="344" alt="Captura de Pantalla 2022-10-16 a la(s) 17 38 50" src="https://user-images.githubusercontent.com/62019329/196057461-47343e58-601d-43fd-801b-648b8d79bce6.png">

Y por los test que he estado realizando creo que afecta en los resultados que podría tener en las respuestas finales.

**Comment by Skablop** [comment]
Hola,

Es cierto que no es bueno mezclar int con bool en algunos contextos, pero en este caso particular no afecta. Esto ya que en python 3.x la comparación True==1 y False==0 son ciertas. Puedes ver más info 
[https://stackoverflow.com/questions/2764017/is-false-0-and-true-1-an-implementation-detail-or-is-it-guaranteed-by-the](en este link) 


Saludos.
