### ISSUE TITLE
T2 P1.1

### ISSUE THREAD

**Issue by kunafuego** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#44]
Hola! Quisiera saber cuál es la diferencia entre los tests testX.txt y los text_anytimeX.txt. ¿Se supone que en los para anytime el usuario debería ser capaz de encontrar una segunda solución? O deberían ser solucionables con una determinada cantidad de expansiones?

Si me pudieran aclarar la diferencia entre los dos tipos de tests se los agradecería mucho, gracias!

**Comment by vicentevegaulloa** [comment]
Hola! La gracia de los tests_anytime es que son más grandes y toman más tiempo en ser resueltos. Pero puedes usar cualquier test para probar cualquier algoritmo. Podría pasar que no encuentres una segunda solución en algunos y no hay problema. Lo que más importa es la implementación.
