### ISSUE TITLE
[T2 - P2.3] Uso de podas

### ISSUE THREAD

**Issue by mateogs** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#45]
Hola,
en la pregunta 2.3 se deben hacer pruebas utilizando nuestra implementación de Minimax, pero no me queda claro si se debe hacer uso de la poda Alfa-Beta.

**Comment by tomascortes** [comment]
Hola!
Lo esperado es que el estudio analítico sea con la implementación de las podas alpha beta. 
Si no lograste implementarlas, hazlo de todas formas con tu implementación de MinMax
