### ISSUE TITLE
T2 P1.3

### ISSUE THREAD

**Issue by Fuentes149** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#47]
Hola tengo una duda sobre las heuristicas, cuando una heuristica es mejor creo otra es porque encuentra valores mas cercanos a la verdadera cantidad de movimientos para llegar a la solucion, osea la mejor heuristica que se podria tener es una que retorne el valor exacto de movidas para llegar a la solucion?

**Comment by sebaguerrap** [comment]
Hola @Fuentes149 . Hay distintas métricas bajo las cuales se puede medir la calidad de una heurística. Podemos decir que una heurística es mejor que otra si tiene que recorrer menos nodos para llegar a una solución. Sin embargo, podría ser muy costoso calcular el valor de la heurística en cada nodo expandido por lo que, aunque la heurística recorra menos nodos, podría tomar más tiempo a tu computador llegar a la solución.

En el caso de heurísticas admisibles, usando A*, estas siempre llegaran a soluciones óptimas, sin embargo podrían tener que expandir más o menos nodos. La mejor heurística posible sería una que expanda la misma cantidad de nodos que movimientos hay que hacer para llegar a la solución. Sin embargo, habría que considerar también el tiempo que toma al computador llegar a la solución, por lo que esta heurística podría no ser la mejor.
