### ISSUE TITLE
T2 - P1.1.5 Poda

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#48]
Hola! tengo una duda con la poda que se propone para la parte 1.1.5. Al darle muchas vueltas creo que la poda no beneficia la ejecución, al probarlo empíricamente tampoco obtengo buenos resultados. Por eso quería saber si esa poda presenta errores o debo seguir intentando aplicarla. Además, tengo una duda de qué es el C_ult que se habla en el enunciado específicamente. En una issue señalaron que es el g del nodo, pero no me queda claro si este valor se actualiza o queda fijo desde que se encuentra.

Muchas gracias de antemano.

**Comment by sebaguerrap** [comment]
Hola @SebaHagedorn . C_ult corresponde a el g del nodo, es decir, la cantidad de movidas que deben efectuarse para llegar a la solución. Este valor depende de cuál fue la última solución encontrada así que podría ir cambiando durante la ejecución a medida que se van encontrando soluciones. En cuanto a la poda, es necesario implementarla, puede que esto no implique mejores resultados pero no me imagino que pueda empeorar los resultados.

**Comment by SebaHagedorn** [comment]
Hola @sebaguerrap, gracias por tu respuesta. Sigo teniendo dudas, porque para todos los nodos de open, es claro que su g va a ser mayor que el Cult porque no se ha llegado a la solución y no puede ser que la solución después del limite de expansiones tenga menos movimientos. Por favor si me puedes decir si estoy entendiendo mal el problema o la poda te lo agradecería mucho.

**Comment by sebaguerrap** [comment]
Hola, el valor de g de los nodos de open no es obligatoriamente mayor que C_ult ya que al usar weighted A* no siempre se llega a una solución óptima. Ilustrándolo con un ejemplo, puede que la solución óptima tenga costo de 10 pero obtengamos una solución con costo 12 en una iteración del algoritmo. En este caso, en open quedarán nodos con g menor a 12. Puede que nunca hayamos expandido un nodo con g de 4 por ejemplo ya que f=g+w*h podría ser muy alto.

**Comment by SebaHagedorn** [comment]
Gracias! Creo que me quedó más claro
