### ISSUE TITLE
T2 -P1.2 Demostrar Admisibilidad

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#49]
Dependiendo del test que usemos f va a dar valores distintos, entonces una heurística puede ser admisible en un test y no admisible en otro?

**Comment by sebaguerrap** [comment]
Hola @vice-rosas99 . Dependiendo del nodo se obtendrá un valor de f distinto, es perfectamente normal tener valores de f distintos dependiendo del test. Sin embargo, la admisibilidad de la heurística no depende de los test.
