### ISSUE TITLE
[T2-P1.1] Límite de expansiones sin solución encontrada

### ISSUE THREAD

**Issue by totoiii** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#50]
Holaa 
![Screenshot_1](https://user-images.githubusercontent.com/69605379/196587707-a91303d7-7959-4d15-a00f-4b20843eb66f.png)

Tengo una duda respecto a  esta parte del enunciado, pueden haber casos en los que se haya alcanzado el limite de expansiones y aun no exista solución, entonces, mi duda es qué es lo que debemos retornar en ese caso?  O asumimos que siempre existirá una solución encontrada a la hora de llegar al límite de expansiones?

**Comment by vicentevegaulloa** [comment]
Hola! Perfectamente podría pasar. De hecho si le pones un máximo de 2 expansiones va a pasar. En ese caso lo que retorne queda a tu criterio. Esto puede ser un None, un int, o cualquier otra cosa siempre y cuando tu programa no se caiga. Recuerda explicarlo bien, para que se entienda cómo estás manejando ese caso. Éxito en la tarea!
