### ISSUE TITLE
T2 P1: Influencia del weight

### ISSUE THREAD

**Issue by mpspanakakis** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#51]
Hola, una duda con respecto a los pesos de A* para relajar la búsqueda.
Si ejecuto la implementación de A* con diferentes pesos, siempre se encuentra la misma solución. Esto hace que sea un poco difícil probar Anytime A*. ¿Es cierto que no aparece ninguna solución subóptima para pesos grandes?
Gracias!

**Comment by sebaguerrap** [comment]
Hola @mpspanakakis . Puede pasar que independiente del peso de la heurística se encuentre siempre la misma solución (óptima). Esto último dependería del tablero inicial.
