### ISSUE TITLE
[T2 P1.1] duda extract

### ISSUE THREAD

**Issue by mhrobles** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#52]
Tengo duda sobre la funcion extract, esta se supone que extrae el nodo con menor valor f? y una vez que se extrae, no se elimina de self.open, o si?

**Comment by sebaguerrap** [comment]
Hola @mhrobles . El método ```extract``` extrae el nodo con el menor valor f y lo elimina de ```self.open```.
