### ISSUE TITLE
T2 P1.3

### ISSUE THREAD

**Issue by jcarrascoa7** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#54]
Hola, tengo un par de dudas respecto a la comparación de las heurísticas.

- La comparación tiene que hacerse utilizando el algoritmo `anytime` o podemos utilizar cualquiera?
- En caso de tener que realizarse con `anytime`, los valores a comparar (cantidad de nodos expandidos y tiempo de ejecución) deben ser para encontrar la primera solución o se busca comparar las heurísticas a través de la búsqueda sucesiva de soluciones?

**Comment by sebaguerrap** [comment]
Hola @jcarrascoa7 . La comparación debe hacerse con A* (el que viene implementado en ```solver.py```). Sin embargo, si ya lo hiciste con ```anytime``` debes especificarlo.
