### ISSUE TITLE
T2 P1.1: Nodo con menor valor después de la poda

### ISSUE THREAD

**Issue by Maxi1805** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#55]
Hola, tengo una duda sobre devolver soluciones en la pregunta 1.1. En el enunciado se menciona que después de conseguir la primera solución no expandiremos, ni agregaremos al open, nodos con peor valor que la solución, sin embargo, ¿qué pasa con los nodos que se encuentran dentro del open y son soluciones del problema?, ¿debemos enviarlos o enviar el último resultado?

**Comment by Maxi1805** [comment]
Sisi, entiendo lo del yield, me referia a que si, despues del primer retorno, debemos devolver todos los nodos que sean soluciòn que se encuentren dentro del open o solo los que sean iguales o menores a la anterior solución encontrada.

**Comment by sebaguerrap** [comment]
Debes retornar la mejor solución encontrada hasta el momento
