### ISSUE TITLE
Duda actividad 1.1 nueva solución

### ISSUE THREAD

**Issue by sebaterrazas** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#56]
Hola!
No entiendo de que manera el usuario puede solicitar una nueva solución al algoritmo. ¿Se espera que al correr nuestro programa, después de encontrar una solución, le pidamos un input al usuario sobre si se quiere continuar la búsqueda? ¿o solo se espera que creemos un archivo nuevo con la clase Anytime que sirve para implementar el algoritmo?

Además, en el punto 2 de esa misma actividad, dice que "a búsqueda siempre es interrumpida cuando el límite de expansiones ha sido alcanzado". ¿A qué límite se refiere? ¿es un argumento que se le tiene que entregar al algoritmo?

**Comment by sebaguerrap** [comment]
Hola @sebaterrazas . Cuando usas ```yield``` puedes correr de nuevo la función desde donde se dejó, es decir, no parte de nuevo sino que retoma de donde se paró la ejecución. Un ejemplo de como se puede hacer uso de ```yield``` es el siguiente:

```python
def contador_hasta_6():
    n = 0
    while n < 6:
        n = n + 1
        yield n


    for num in contador_hasta_6():
        print(num)
```

Si te fijas, en el ejemplo anterior puedes iterar sobre los outputs de la función. Es tu deber crear un archivo donde se pueda correr este algoritmo y explicitarlo en tu PDF de respuestas. No es necesario pedirlo como input, puedes dejarlo como parámetro. Te dejo un ejemplo de como podrías pedir 3 respuestas usando la misma función del ejemplo anterior:

```python
contador = contador_hasta_6()
for i in range(3):
    print(next(contador))
```

Sobre el límite de expansiones, este debe ser un argumento que se le debe entregar al algoritmo.
