### ISSUE TITLE
[Test Formativo] Pregunta 9 

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#59]
Hola!! Tengo una duda respecto a la pregunta 9 del test formativo, el motivo por el que la primera afirmación es incorrecta es debido a que como dice que obtiene resultados buenos en el test de entrenamiento y malos en el set de test significa que se está "sobre-entenando", es decir pierde su capacidad de generalidad, y esto se puede deber a que los árboles tienen poca diversidad y esto último indica que tienen un alto nivel de strength? Adjunto una imagen de la pregunta.
![Captura de pantalla (114)](https://user-images.githubusercontent.com/62029138/197244837-0bcfec73-33fa-4cc6-a389-0839859e30e6.png)

**Comment by sebaguerrap** [comment]
Hola @RonaldoSosa . En las slides de clases nos mencionan que la generalización (GE) de un Random Forest está acotada por la correlación media entre pares de árboles $(\phi)$ y el *strength* del ensamble $(S)$ por la siguiente inecuación:

$GE\leq \phi \frac{1-S^2}{S^2}$

Es por esto que si tenemos buen rendimiento en el set de entrenamiento y mal rendimiento en el set de test se debe a que nuestro modelo no está generalizando bien. Ahora bien esto puede deberse a baja correlación o alto *strength*.

**Comment by RonaldoSosa** [comment]
Valeee, me quedo claro. Gracias!
