### ISSUE TITLE
[T3-P1]

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#62]
Para limpiar los datos, ¿es necesario comprobar que todos los datos de todas las columnas tienen valores correctos o podemos asumir que lo son? Por ejemplo, comprobar que en la columna "Age" todos los valores son números y están entre 1 y 13.

**Comment by vicentevegaulloa** [comment]
Hola!

La idea es que revises todas las formas de validar los datos. Dado que están "sucios", tu eres quien debe validar lo mínimo con lo que debe cumplir cada columna. Esto quiere decir que en el ejemplo que propones, sí debes revisar que la edad esté en un rango razonable.
