### ISSUE TITLE
[T3-P3] División de los datos

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#63]
En la actividad 3 se pide dividir los datos en entrenamiento-test, pero posteriormente se dice que usemos el set de validación para mejorar los hiperparámetros de los modelos. ¿Hay que dividir los datos en entrenamiento-validación-test o solamente en entrenamiento-test?

**Comment by vicentevegaulloa** [comment]
Hola! 

Los datos de entrenamiento son para preparar a tu modelo y posteriormente ver como rinde con los datos del set de test. El set de validación podría verse como un subconjunto del set de entrenamiento que se utiliza para probar con diferentes hiperparámetros y dentro del entrenamiento.

Es válido hace una separación entrenamiento-validación-test o entrenamiento-test y posteriormente separar entrenamiento en entrenamiento-validación.
