### ISSUE TITLE
[T3] Columna AnyHealthcare

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#64]
Holaaa! En db_diabetes.csv aparece una columna llamada AnyHealthcare pero esta no es mencionada en el enunciado. Indica si la persona en cuestión realizo algún cuidado de su salud durante un periodo de tiempo?

**Comment by BrunoFarfan** [comment]
Hola, esa columna lamentablemente se nos pasó en el enunciado.
**AnyHealthcare: Indica si una persona tiene cualquier tipo de plan de salud, 1 = sí, 0 = no.**
Si la borraste ya, y tu modelo cumple con el porcentaje pedido en el enuciado, no hay problema.
