### ISSUE TITLE
[T3 - P1.5] Datos para entrenar tercer árbol

### ISSUE THREAD

**Issue by aplaza2** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#66]
Hola, tengo un problema en esta parte al intentar entrenar el tercer árbol de decisión. En el enunciado se pide entrenar esta con los datos que el segundo árbol haya clasificado mal, pero por alguna razón dicho árbol me clasifica todos los datos restantes correctamente y me quedo sin datos para entrenar el tercer árbol. ¿Es esto siquiera posible o es un error de implementación? Y en caso de que sea posible (a pesar de lo inusual), ¿debo considerar alguna parte de los datos para entrenar al tercer árbol o lo omito?

Gracias de antemano!

**Comment by BrunoFarfan** [comment]
Hola!

Como esta situación no está en el enunciado, puedes tratarla como más te acomode. Si quieres, simplemente omite el tercer árbol.
