### ISSUE TITLE
[T3] Accuracy árbol de decisión

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#67]
En las actividades 4 y 6 (usando en la 6 un random forest de 3 árboles) obtengo un accuracy muy alto: 0.999. ¿Es normal que obtenga estos valores o es probable que esté haciendo algo mal? Si esto puede ocurrir, no tengo forma de comparar ambos modelos.
Muchas gracias!

**Comment by BrunoFarfan** [comment]
Hola!

No hay ningún problema con que obtengas valores muy altos mientras estés realizando bien todo lo pedido en el enunciado. Igualmente recuerda que se pide comparar en base a 3 métricas y que se espera que se calculen sobre el **set de test**.
En caso de que no haya diferencia entre modelos, puedes intentar explicar por qué crees que pasa eso
