### ISSUE TITLE
[T3-DCCaracteres] Leer archivo csv

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#68]
En las instrucciones de la tarea se indica que no se debe subir el dataset al repositorio. En DCClínica no hay problema con leer el archivo directamente de drive sin necesidad de descargar nada, pero el csv de DCCaracteres es demasiado grande y google drive indica que no puede analizar los virus. Esto hace que no me permita leer el csv directamente. La solución que he encontrado es utilizar "gdown" para descargar el csv y luego leerlo. Esto no incluye directamente el csv en el repositorio, sino que lo descarga de manera local antes de almacenarlo en el dataframe. ¿Se puede hacer esto o tampoco está permitido?
Muchas gracias!

**Comment by tcouso** [comment]
Hola! Lo importante es que el archivo no quede almacenado en tu repositorio. Mientras te asegures de que eso sea así, puedes usar el método que prefieras. Saludos!
