### ISSUE TITLE
T3 P 1.5

### ISSUE THREAD

**Issue by brayan788** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#69]
Hola no entiendo eso de entrenar el primer arbol con todo, pq despues con que lo testeo para ver en que se equivoco, tengo la misma duda con el segundo arbol con que lo testeo para ver en que se equivoca?

**Comment by BrunoFarfan** [comment]
La idea es que tengas un set de train. Ese lo usas para entrenar el primer árbol y luego predecir sobre ese mismo set.
El segundo árbol se entrena **solamente** con los datos que el primero predice mal sobre el set de train. Después el 2do árbol predice sobre el **mismo** set con el que él se entrenó y los que **predice mal** pasan al tercer árbol, el cual finalmente se entrena únicamente con estos.

**Comment by EleaTriesToCode** [comment]
Si igual, tengo dudas sobre lo que significa "entrenar el arbol con todos los datos"...
Hay que crear sets de test y de entrenamiento igual o no ? Si es que si, con qué proporcion ? Lo normal o mas como 50%-50% para dar mas datos a los siguientes arboles ? 
Y si no, es posible que no existe un set de entrenamiento para este arbol

**Comment by totoiii** [comment]
Hola! no estoy muy de acuerdo sobre lo que dicho en esta issue especificamente en:
" el 2do árbol predice sobre el mismo set con el que él se entrenó"
 ya que si se predice sobre los mismos datos sobre los que se entrena, se tendrá un accuracy del 100%. No me queda claro cómo obtener el set de testeo en cada árbol para poder predecir sobre este.

**Comment by vicentevegaulloa** [comment]
Hola @totoiii, 

Lo que dices no es del todo cierto. Un modelo entrenado busca generalizar sobre la data con la que se entrena. Esto quiere decir que probablemente falle al predecir un outlier aunque ya lo haya visto. La única forma en la que el modelo obtenga 100% de accuracy al ser evaluado sobre el set de entrenamiento es que los datos sean demasiado fáciles de separar o que el modelo esté haciendo overfitting.

Por último, recuerda que el ensamble en sí es un modelo también, por lo que los datos con los que se entrena sirven para testear sus sub-arboles pero el ensamble en sí debe ser tesetado con su set de test.

**Comment by totoiii** [comment]
Pero entonces para el caso del arbol 2 y del arbol 3, se debe testear
respecto a sus datos de entrenamiento también o respecto a los datos
iniciales entregados en fit?

**Comment by vicentevegaulloa** [comment]
El arbol 1 se entrena con todos los datos del set de entrenamiento de tu ensamble. Luego, lo testeas con los mismos datos (todo el set de entrenamiento del ensamble). 

El arbol 2 se entrena con los datos mal clasificados del arbol 1. Luego, se testea con los mismos datos mal clasificados del arbol 1.

El arbol 3 se entrena con los datos mal clasificados del arbol 2. Luego, se testea con los mismos datos mal clasificados del arbol 2.

Espero que ahí haya quedado más claro.
