### ISSUE TITLE
[Tarea 1] Tiempo de ejecución

### ISSUE THREAD

**Issue by aplaza2** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#7]
Hola, tengo una duda sobre la ejecución de clingo. Me pasa que cuando ejecuto el programa de la pregunta 1 bajo ciertas condiciones me queda calculando de forma indefinida sin darme respuesta (ya más de 20 minutos). ¿Hay alguna forma de saber qué restricciones causan ese problema o alguna forma de restringir el tiempo de ejecución?

**Comment by vicentevegaulloa** [comment]
Hola @aplaza2!

Creo que no existe una forma sofisticada de revisar esto (como un debugger de clingo). Lo que haría en tu caso si con inspección no te funciona, es que dado que las pistas son independientes entre si, da lo mismo si corres tu código comentando la pista 1 o la pista 10. Es por esto que lo mejor que se me ocurre por ahora es que vayas comentando las pistas una a una hasta que encuentres donde se dispara el tiempo de ejecución.

Ojalá eso te funcione. De todas formas seguiré pensando en mejores formas de debuggear tu código. Te comento si encuentro algo :)
