### ISSUE TITLE
T3 - SVM, escalar los datos

### ISSUE THREAD

**Issue by EleaTriesToCode** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#70]
Hola !
No entiendo muy bien lo del escalamiento de los datos en la parte 2 sobre los SVMs.
Debemos traducir los valores de cada pixel a un valor float entre 0 y 1 ? O significa algo distinto ?

**Comment by tcouso** [comment]
Hola! Escalar los datos es llevar los valores a un mismo rango acotado (0 a 1, -1 a 1, etc.) Lo importante es que especifiques qué método de escalamiento decidiste usar, y que también fundamentes la importancia de escalar datos en SVM. Recomiendo que revises la documentación de sklearn para encontrar más información sobre esto. 
Saludos!

**Comment by EleaTriesToCode** [comment]
Gracias ! 
Entiendoen general porque es importante escalar los datos, pero todavia no me quedo claro cual escalamiento seria mejor usar... 
Podemos o dividir todos los datos por 255 o usar scalers especificos como el MinMaxScaler que parece bastante común. Tienes consejos sobre que considerar para hacer nuestra eleccion de scaler ? :)

**Comment by tcouso** [comment]
Te recomiendo probar un par de scalers y visualizar las imágenes que te quedan con los datos escalados, eso debería ayudarte a distinguir mejor cuál usar. En todo caso, hay más de un scaler que podría servirte, por lo que tampoco te preocupes tanto por esa decisión. Lo importante es que en la justificación de escalar los datos hagas referencia a por qué es importante hacer esto en SVM (aludiendo a elementos concretos del funcionamiento del algoritmo).

Saludos y éxito!
