### ISSUE TITLE
[T3-P 1.5] Funcionamiento Random Forest

### ISSUE THREAD

**Issue by cristinalopezamado** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#71]
Hola,
No se si estoy entendiendo bien cómo se entrena el Random Forest que hay que construir. Por lo que pone en el enunciado, entiendo que hay que entrenar y testear cada uno de los árboles con los datos de entrenamiento, pero ¿un árbol de decisión en el que no fijas una profundidad máxima no va a clasificar siempre bien los datos de entrenamiento? De hecho, eso es precisamente lo que pasa en mi código: no hay datos mal clasificados y entonces no puedo entrenar el segundo árbol.

**Comment by BrunoFarfan** [comment]
La idea es que busques la forma de poder entrenar los 3 (limitar la profundidad si es necesario) y obtener la mayor accuracy posible.
Si igualmente no logras entrenar los 3, queda a tu criterio como trabajarlo.
