### ISSUE TITLE
T3 P1.2 Consulta conocimientos previos

### ISSUE THREAD

**Issue by totoiii** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#72]
Tengo una consulta, ¿puedo ocupar ciertos conocimientos básicos acerca de los datos que se entregan para descartar o no columnas?, por ejemplo, yo se que la informacion entregada por el indice de masa corporal ocupa la del peso y la estatura, entonces podira eventualmente eliminar una columna debido a esto.

**Comment by tcouso** [comment]
Hola!

Mientras justifiques adecuadamente tus decisiones (tal como hiciste con el ejemplo del IMC), puedes efectivamente descartar columnas que consideres irrelevantes.

Saludos!
