### ISSUE TITLE
[T3] -  P1:  problemas con "Diabetes_binary"

### ISSUE THREAD

**Issue by kvonstorch** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#73]
¡Hola! 
He estado trabajando en la parte 1 de la tarea con la librería pandas y he tenido problemas al acceder a la columna "Diabetes_binary",  tanto en funciones, como para discretizar. Usualmente se produce KeyError(key). Verifique que el data tuviera la key efectivamente no sale. He intentado solucionarlo de varias formas, pero aun no he tenido éxito. ¿Saben que puedo hacer al respecto?.
Agradezco de antemano. :v:

**Comment by BrunoFarfan** [comment]
Hola!

Podrías hacer un print de tu dataframe de pandas y mandarlo para intentar ver qué es lo que sucede?
Con la descripción que diste no logro entender bien qué podría fallar

**Comment by kvonstorch** [comment]
![image](https://user-images.githubusercontent.com/69520619/200924521-297a046d-2250-4298-99e6-aaf9ebcffe70.png)
![image](https://user-images.githubusercontent.com/69520619/200924738-aa1f06b4-88ac-40b4-a64f-42e72870e3b8.png)
Eso esta bien?

**Comment by kvonstorch** [comment]
![image](https://user-images.githubusercontent.com/69520619/200924917-83ad3d16-8510-4e71-b052-8e6ce4d62da0.png)
![image](https://user-images.githubusercontent.com/69520619/200925079-0ffb9108-922f-4d4b-8eb8-eeb3e76feea1.png)
Eso sirve?

**Comment by BrunoFarfan** [comment]
Creo que lo más probable es que haya algún error al importar el dataset en python. También puede ser que por alguna razón estés manejando mal el archivo con los datos, por lo que te recomendaría partir revisando el código, y sino probar importarlo en otra parte. Por ejemplo si estás en colab, intentar importarlo en vscode.

**Comment by kvonstorch** [comment]
Yap, voy a seguir probando, lo importe como en la ayudantía.

**Comment by kvonstorch** [comment]
Solucionado, gracias.
