### ISSUE TITLE
[T3] 1.3

### ISSUE THREAD

**Issue by Fuentes149** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#74]
Hola en varias partes de la tarea piden que investiguemos, los resultados de la investigación hay que entregarlos en un archivo pdf con la tarea o solo lo comentamos en el código?

**Comment by tcouso** [comment]
Hola! Se espera que las respuestas de desarrollo en las que investigues sean celdas de texto en tu notebook. Recuerda también incluir los links/referencias que uses. 

Saludos!
