### ISSUE TITLE
[T3] agregar columnas de datos

### ISSUE THREAD

**Issue by jo00** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#75]
Hola es posible que agregar una columna de datos, que por ejemplo relacione dos columnas ya existentes si pensamos que puede ser de mayor utilidad a la hora de limpiar los datos? o esto no es realmente necesario?

**Comment by BrunoFarfan** [comment]
Hola!

Puedes hacerlo siempre y cuando des una justificación de por qué lo haces, ya que realmente no le estarías agregando información nueva.
