### ISSUE TITLE
T3 P1.2 Graficar los datos

### ISSUE THREAD

**Issue by totoiii** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#77]
Hola, tengo una duda en cuanto al formato de los gráficos que se piden en esta parte. He mostrado muchas tablas del comportamiento de Diabetes_binary respecto a diversas categorías que considero que son relevantes mostrarlas, y también entre categorías y otras.  Mi duda es, ¿a esto se refieren con graficar? O quieren que haga algo más que mostrar tablas, como un ploteo de algo o nose.
Saludos

**Comment by BrunoFarfan** [comment]
Con tablas basta si es que aportan la información necesaria y realmente aportan una buena forma de visualizar los datos.

Ahora para los gráficos, podrías por ejemplo graficar probabilidades de tener diabetes en eje Y, y el BMI en el eje X.
Sin embargo, es solo una idea y si crees que ya tienes suficientes recursos visuales (tablas, gráficos, etc), no es necesario
