### ISSUE TITLE
[T3 P2] CSV

### ISSUE THREAD

**Issue by LaSamada** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#78]
Hola!, para cargar el csv de la pregunta 2 de los caracteres, he tenido problemas para hacerlo directamente de google drive, es posible que se indique en el cuadernillo que se tiene que agregar el archivo caracteres.csv cuando se revise la pregunta para que este funcione ?(y así no subirlo al repositorio).

**Comment by tcouso** [comment]
Hola!

No estoy seguro de si entendí tu pregunta, pero si tienes problemas para incluir el archivo directamente desde google drive, puedes descargarlo y asegurarte de no incluirlo en tu repositorio (por ejemplo, mediante un archivo ```.gitignore```). Si haces eso, recuerda indicar en tu ```README```  la ruta relativa en la que debería encotrarse el archivo para que el notebook pueda correr adecuadamente.

Saludos!
