### ISSUE TITLE
[Tarea 1] Definir de el "lado" (pista 11 y 12)

### ISSUE THREAD

**Issue by ferperezh** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#8]
Hola en la pregunta 11 y 12 hablan de que un programador que esta al lado de otro, entonces me preguntaba si puedo definir estáticamente que lado puede ser para cada pregunta. Por ejemplo, poner que "La persona que toma RedBull está sentada al lado **derecho** de la persona que escucha Jazz."". Evidentemente ajustarlo de manera que me entregue una solución. Sino se puede como puedo poner en clingo un or?

**Comment by vicentevegaulloa** [comment]
Hola @ferperezh!

Si la pista dice que está al lado sin especificar si es derecha o izquierda, podría ser cualquiera de los dos. El "or" en clingo se representa con dos reglas con la misma cabeza. Por ejemplo:

```
p :- q.
p :- s.
```
Las dos reglas de arriba quieren decir que `p` estará en el modelo si `q` o `s` están en el modelo. 

De todas formas quisiera recordarte algo importante de clingo y de la lógica en general. Hay varias formas de representar lo mismo. Por ejemplo, en el caso de tu duda, podrías decir que "el que toma RedBull está a la derecha o izquierda del que escucha Jazz" o también podrías decir "el que toma RedBull NO está a mas de un puesto de distancia del que escuhca Jazz". Espero que ese consejo te sirva para esta pregunta y las demás :)

Si algo no queda claro me avisas!

**Comment by morbeta1234** [comment]
Hola! En relación a esto mismo, no me queda claro si deberíamos considerar como "al lado" como, por ejemplo, 2 está al lado de 1 y 3 (mirandolo como una recta), o se debiese considerar de otra forma? @vicentevegaulloa

**Comment by vicentevegaulloa** [comment]
Hola @morbeta1234 !

Es efectivamente eso. Los programadores están sentados en fila. Esto quiere decir que el 1 está al lado del 2, el dos al lado del 1 y el 3, el 5 al lado del 4, etc.
