### ISSUE TITLE
[T3 P2.2]

### ISSUE THREAD

**Issue by Fuentes149** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#80]
Hola tengo un problema al visualizar los caracteres me aparece el siguiente error:

![Captura de Pantalla 2022-11-08 a la(s) 22 29 17](https://user-images.githubusercontent.com/89354729/200648565-b0a55b82-83b3-4975-b661-82b03c30042d.png)

**Comment by BrunoFarfan** [comment]
Te recomiendo investigar sobre el método reshape.
El error que te da ahí es porque no es posible convertir un vector de largo 86864 en una matriz de 28x28

**Comment by Fuentes149** [comment]
No entiendo bien que se pide hacer en esa parte de la tarea
