### ISSUE TITLE
T3 1.2

### ISSUE THREAD

**Issue by jcarrascoa7** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#82]
Hola, tengo una duda respecto al tema de la graficación de los datos. Resulta que uno de los gráficos que quiero hacer para verificar que alguna columna aporte o sea redundante requiere que dicha columna tenga valores numéricos, por lo que estaba pensando en discretizar los datos en este momento. Sin embargo, según el enunciado, dicho paso se tiene que hacer para la actividad 3, no para la 2.

Entonces mi pregunta es ¿lo que se dice en el enunciado es una restricción y no puedo discretizarlos hasta llegar a la actividad 3 o puedo hacerlo de todas maneras y dicho resultado cuenta para la actividad 3?

**Comment by BrunoFarfan** [comment]
Hola!

Puedes hacerlo antes, no hay problema. Solamente menciónalo en la actividad que corresponde, para que quede claro que lo hiciste antes
