### ISSUE TITLE
T3 1.5

### ISSUE THREAD

**Issue by pedroriosg** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#83]
Hola! En la actividad 5 de la parte 1, el accuracy y las métricas del ensamblaje se calculan como el promedio de los tres  árboles?

**Comment by BrunoFarfan** [comment]
Hola!

En el enunciado explica que los 3 árboles actúan como un RandomForest, donde cada árbol "vota", por lo que las métricas tienes que calcularlas sobre el resultado de la "votación"

**Comment by pedroriosg** [comment]
Con lo de los pesos? No me queda claro todavía
