### ISSUE TITLE
T3 P1.5

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#85]
Hola, una duda en cuando estamos en el entrenamiento del ensamblador, tenemos que al primer árbol le damos todos los datos del set de entrenamiento y después este debe hacer una predicción, pero mi duda es, esta predicción debe ser sobre todo el set de entrenamiento o sobre un set de validación, que nosotros definimos?

Después tenemos que el segundo árbol se entrena sobre los datos que se equivoco en clasificar el primer árbol, pero este al predecir debe utilizar la misma data para predecir el primer árbol?.

**Comment by vicentevegaulloa** [comment]
Hola @Kevinnevik, 

Como se explica en la issue #69, debes entrenar el primer arbol sobre todo el set de entrenamiento y evaluarlo sobre el mismo set de entrenamiento. Para el segundo árbol debes hacer lo mismo que para el primero, pero el set con el que lo entrenas y lo testeas es el set compuesto por las datos que clasificó mal el primer árbol.
