### ISSUE TITLE
[Tarea 1 P2] Curso aprobado no puede tener semestre asignado

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2613-Inteligencia-Artificial-2022-2/Syllabus#9]
Hola! En la Tarea 1 Actividad 2, no me queda muy claro a qué se refiere la regla "Los cursos aprobados no pueden tener un semestre asignado". 
Se refiere a que si un curso C ya fue aprobado, entonces no puede existir ningún átomo ```course_on(C, X)``` ? O se refiere a otra cosa?

**Comment by vicentevegaulloa** [comment]
Hola @CrisBerriosL ! 

Es exactamente eso, si un curso C ya fue aprobado, entonces no puede existir ningún átomo course_on(C, X).
